print(' FAÇA A TABUADA DE UM NÚMERO QUALQUER.')
n = int(input('Digite um número qualquer:'))
print('A tabuada desse número será:')
print('x1={}'.format(n*1))
print('x2={}'.format(n*2))
print('x3={}'.format(n*3))
print('x4={}'.format(n*4))
print('x5={}'.format(n*5))
print("x6={}".format(n*6))
print('x7={}'.format(n*7))
print('x8={}'.format(n*8))
print('x9={}'.format(n*9))
print('x10={}'.format(n*10))
print(' ESSA SERÁ A TABUADA DESSE NÚMERO ')
print('DESAFIO 09 RESOLUÇÃO 02, CONCLUIDO!')