print('Crie um programa que leia o nome completo de uma pessoa e mostre:')
print('=====================================================')
print('1>O nome com todas as letras maiúsculas')
print('=====================================================')
print("2>O nome com todas as letras minúsculas")
print('=====================================================')
print("3>Quantas letras ao todo ( sem considerar espaços )")
print('=====================================================')
print('4>Quantas letras tem o primeiro nome.')
print('===================================================================')
print('===================================================================')
nome = str(input('Qual o seu Nome?')).strip()
print('=============================')
nome = nome.upper()
print('1-O nome com todas as letras maiúsculas:', nome)
print('===============================================')
nome = nome.lower()
print('2-O nome com todas as letras minúsculas:', nome)
print('===============================================')
nome = len(nome)
print('3-Quantas letras tem o nome ao todo?', nome)
print('================================================')
nome =('Gustavo')
print('4- Quantas letras tem o primeiro nome:', nome)
print('====================================================================')
print('====================================================================')
print('DSAFIO 22 AULA 09 CONCLÚIDO!')
