print('=========================================ATIVIDADE=======================================================')
print('Crie uma tupla preenchida com os 20 primeiros colocados da Tabela do Campeonato Brasileiro de Futebol ')
print('na ordem de colocação. Depois mostre:')
print('a) Os 5 primeiros times.')
print('b) Os últimos 4 colocados.')
print('c) Times em ordem alfabética.')
print('d) Em que posição está o time da Chapecoense.')
print('=='*40)
times = ('Corinthians', 'Palmeiras', 'Santos', 'Grêmio', 'Cruzeiro' , 'Bahia', 'Vitoria', 'São Paulo', 'Chapecoense','Atletico Mineiro')
for t in times:
    print('=='*40)
    print(t)
print(f'Os cinco primeiros times são: {times[0:5]}.')
print('=='*40)
print(f'Os quatro últimos times são: {times[-4:]}')
print('=='*40)
print(f'Times em ordem alfabética:{sorted(times)}')
print('=='*40)
print(f'O Chapecoense está na {times.index("Chapecoense")+1} posição.')
print('==========================')
print('FIM DO PROGRAMA...')

