print('ALUGUEL DE CARROS.')
print('================================================')
print('Escreva um programa que pergunte a quantidade de KM percorridos por um carro alugado e a quantidade de dias pelos quais ele...')
print('foi alugado. Calcule o preço a pagar, sabendo que o carro custa 60R$ por dia e R$ 0,15 por KM rodado!')
dias = float(input('Qual a quantidade de dias que ele foi alugado?'))
km = int(input(' A quantidade de KMs que ele rodou:'))
pago =(dias*60)+(km*0.15)
print(' O total a pagar é de: {:.2f} R$ '.format(pago))
print(' ================================================')
print(' DESAFIO 15 CONCLUIDO! Nesse precisei de ajuda...enunciado um pouco mais complexo!')